In [ ]:
# Type I
weight=0.1
def neural_network(input,weight):
  prediction=input*weight
  return prediction

In [ ]:
number_of_toes=[8.5,9.5,10,9]
input=number_of_toes[0]
pred=neural_network(input,weight)
print(pred)

0.8500000000000001


In [ ]:
#Type II
def w_sum(a,b):
  assert(len(a)==len(b))
  output=0
  for i in range(len(a)):
    output+=(a[i]*b[i])
  return output

In [ ]:
def neural_network1(input,weight):
  pred=w_sum(input,weights)
  return pred

In [ ]:
weights=[0.1,0.2,0]
toes=[8.5,9.5,9.9,9.0]
wlrec=[0.65,0.8,0.8,0.9]
nfans=[1.2,1.3,0.5,1.0]
input=[toes[0],wlrec[0],nfans[0]]
pred=neural_network1(input,weights)
print(pred)

0.9800000000000001


In [ ]:
#Type III
import numpy as np

In [ ]:
def neural_network2(input,weights):
  pred=input.dot(weights)
  return pred

In [ ]:
weights=np.array([0.1,0.2,0])
toes=np.array([8.5,9.5,9.9,9.0])
wlrec=np.array([0.65,0.8,0.8,0.9])
nfans=np.array([1.2,1.3,0.5,1.0])
input=np.array([toes[0],wlrec[0],nfans[0]])
pred=neural_network2(input,weights)
print(pred)

TypeError: ignored

In [ ]:
#Type IV
def ele_mul(number,vector):
  output=[0,0,0]
  assert (len(output)==len(vector))
  for i in range(len(vector)):
    output[i]=number*vector[i]
  return output

In [ ]:
weights=[0.3,0.2,0.9]

In [ ]:
def neural_network2(input,weights):
  pred=ele_mul(input,weights)
  return pred

In [ ]:
wlrec=[0.65,0.8,0.8,0.9]

In [ ]:
input=wlrec[0]

In [ ]:
pred=neural_network2(input,weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


In [ ]:
#Type V
weights=[[0.1,0.1,-0.3],
         [0.1,0.2,0.0],
         [0.0,1.3,0.1]]

In [ ]:
def w_sum(a,b):
  assert(len(a)==len(b))
  output=0
  for i in range(len(a)):
    output+=(a[i]*b[i])
  return output

In [ ]:
def vec_mat_mul(vect,matrix):
  output=[0,0,0]
  assert (len(vect)==len(matrix))
  for i in range(len(vect)):
    output[i]=w_sum(vect,matrix[i])
  return output

In [ ]:
def neural_network2(input,weights):
  pred=vec_mat_mul(input,weights)
  return pred

In [ ]:
toes=[8.5,9.5,9.9,9.0]
wlrec=[0.65,0.8,0.8,0.9]
nfans=[1.2,1.3,0.5,1.0]

In [ ]:
input=[toes[0],wlrec[0],nfans[0]]
pred=neural_network2(input,weights)
print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


In [ ]:
#Type VI

          #toes %win #fans
ih_weights=[[0.1,0.2,-0.1], #hid[0]
         [-0.1,0.1,0.9],     #hid[1]
         [0.1,0.4,0.1]]      #hid[2]

In [ ]:
            #hid[0] hid[1] hid[2]
hp_weights=[[0.3,1.1,-0.3], #hurt
         [0.1,0.2,0.0],     #win
         [0.0,1.3,0.1]]     #sad

In [ ]:
weights=[ih_weights,hp_weights]

In [ ]:
def neural_network3(input,weights):
  hid=vec_mat_mul(input,weights[0])
  pred=vec_mat_mul(hid,weights[1])
  return pred

In [ ]:
toes=[8.5,9.5,9.9,9.0]
wlrec=[0.65,0.8,0.8,0.9]
nfans=[1.2,1.3,0.5,1.0]

In [ ]:
input=[toes[0],wlrec[0],nfans[0]]
pred=neural_network3(input,weights)
print(pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


In [ ]:
#Using Numpy
     #toes %win #fans
ih_weights=np.array([[0.1,0.2,-0.1], #hid[0]
         [-0.1,0.1,0.9],     #hid[1]
         [0.1,0.4,0.1]]).T     #hid[2]

In [ ]:
hp_weights=np.array([[0.3,1.1,-0.3], #hurt
         [0.1,0.2,0.0],     #win
         [0.0,1.3,0.1]]).T

In [ ]:
weights=np.array([ih_weights,hp_weights])

In [ ]:
weights1=[ih_weights,hp_weights]

In [ ]:
weights1 #It's incorrect

[array([[ 0.1, -0.1,  0.1],
        [ 0.2,  0.1,  0.4],
        [-0.1,  0.9,  0.1]]),
 array([[ 0.3,  0.1,  0. ],
        [ 1.1,  0.2,  1.3],
        [-0.3,  0. ,  0.1]])]

In [ ]:
weights

array([[[ 0.1, -0.1,  0.1],
        [ 0.2,  0.1,  0.4],
        [-0.1,  0.9,  0.1]],

       [[ 0.3,  0.1,  0. ],
        [ 1.1,  0.2,  1.3],
        [-0.3,  0. ,  0.1]]])

In [ ]:
def neural_network3(input,weights):
  hid=input.dot(weights[0])
  pred=hid.dot(weights[1])
  return pred

In [ ]:
toes=np.array([8.5,9.5,9.9,9.0])
wlrec=np.array([0.65,0.8,0.8,0.9])
nfans=np.array([1.2,1.3,0.5,1.0])

In [ ]:
input=np.array([toes[0],wlrec[0],nfans[0]])

In [ ]:
pred=neural_network3(input,weights)
print(pred)

[0.2135 0.145  0.5065]


In [ ]:
# Feedback
knob_weight=0.5
input=0.5
goal_pred=0.8
pred=input*knob_weight
error=(pred-goal_pred)**2
print(error)

0.30250000000000005


In [ ]:
weight =0.1
def neural_network(input,weight):
  prediction=input*weight
  return prediction

number_of_toes=[8.5]
win_or_lose_binary=[1]

input=number_of_toes[0]
true=win_or_lose_binary[0]

lr=0.01
p_dn=neural_network(input,weight)
e_dn=(p_dn-true)**2
print(e_dn)


0.022499999999999975


In [ ]:
weight =0.1
def neural_network(input,weight):
  prediction=input*weight
  return prediction

number_of_toes=[8.5]
win_or_lose_binary=[1]

input=number_of_toes[0]
true=win_or_lose_binary[0]

lr=0.01
p_dn=neural_network(input,weight-lr)
e_dn=(p_dn-true)**2
print(e_dn)

0.05522499999999994


In [ ]:
weight =0.1
def neural_network(input,weight):
  prediction=input*weight
  return prediction

number_of_toes=[8.5]
win_or_lose_binary=[1]

input=number_of_toes[0]
true=win_or_lose_binary[0]

lr=0.01
p_dn=neural_network(input,weight+lr)
e_dn=(p_dn-true)**2
print(e_dn)

0.004224999999999993


In [ ]:
weight =0.1
def neural_network(input,weight):
  prediction=input*weight
  return prediction

number_of_toes=[8.5]
win_or_lose_binary=[1]

input=number_of_toes[0]
true=win_or_lose_binary[0]

lr=0.01
i=1
for i in range(6):
    p_dn=neural_network(input,weight)
    e_dn=(p_dn-true)**2
    up_prediction=neural_network(input,weight+lr)
    uperror=(up_prediction-true)**2
    down_prediction=neural_network(input,weight-lr)
    downerror=(down_prediction-true)**2

    if (uperror>downerror):
      weight=weight-lr
    if (downerror>uperror):
      weight=weight+lr

In [ ]:
weight

0.12

In [ ]:
#Slide 7
weight=0.5
goal_pred=0.8
input=0.5

for i in range(20):
  pred=input*weight
  error=(pred-goal_pred)**2
  direction_and_amount=(pred-goal_pred)*input
  weight=weight-direction_and_amount
  print("Error:" +str(error) +" Prediction:" +str(pred))

Error:0.30250000000000005 Prediction:0.25
Error:0.17015625000000004 Prediction:0.3875
Error:0.095712890625 Prediction:0.49062500000000003
Error:0.05383850097656251 Prediction:0.56796875
Error:0.03028415679931642 Prediction:0.6259765625
Error:0.0170348381996155 Prediction:0.669482421875
Error:0.00958209648728372 Prediction:0.70211181640625
Error:0.005389929274097089 Prediction:0.7265838623046875
Error:0.0030318352166796153 Prediction:0.7449378967285156
Error:0.0017054073093822882 Prediction:0.7587034225463867
Error:0.0009592916115275371 Prediction:0.76902756690979
Error:0.0005396015314842384 Prediction:0.7767706751823426
Error:0.000303525861459885 Prediction:0.7825780063867569
Error:0.00017073329707118678 Prediction:0.7869335047900676
Error:9.603747960254256e-05 Prediction:0.7902001285925507
Error:5.402108227642978e-05 Prediction:0.7926500964444131
Error:3.038685878049206e-05 Prediction:0.7944875723333098
Error:1.7092608064027242e-05 Prediction:0.7958656792499823
Error:9.614592036015323